// import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Auth from "../components/Auth";

const Login = () => {
  return (
    <div>
      <Head>
        <title>pizza app</title>
        <meta
          name="just a pizza ordering app"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Auth />
      </main>
    </div>
  );
};

export default Login;
